export default (req, res) => {
  res.statusCode = 200;
  res.json([
    {
      id: 1,
      name: "Deluxe",
      condo: true,
      house: true,
      condoPrice: 570.0,
      housePrice: 675.0,
      services: [1, 2, 7, 8, 9, 11, 12],
    },
    {
      id: 2,
      name: "Deluxe Plus",
      condo: true,
      house: true,
      condoPrice: 680.0,
      housePrice: 850.0,
      services: [1, 2, 5, 6, 10, 12],
    },
    {
      id: 3,
      name: "Full Coverage",
      condo: true,
      house: true,
      condoPrice: 385.0,
      housePrice: 450.0,
      services: [1, 2, 7, 8, 9],
    },
    {
      id: 4,
      name: "Full Coverage Plus",
      condo: true,
      house: true,
      condoPrice: 495.0,
      housePrice: 675.0,
      services: [1, 2, 5, 6, 10],
    },
    {
      id: 5,
      name: "Basics",
      condo: true,
      house: true,
      condoPrice: 220.0,
      housePrice: 270.0,
      services: [1, 2, 7, 8],
    },
    {
      id: 6,
      name: "Basics Plus",
      condo: true,
      house: true,
      condoPrice: 320.0,
      housePrice: 450.0,
      services: [1, 2, 5, 6],
    },
    {
      id: 7,
      name: "Full Video",
      condo: true,
      house: true,
      condoPrice: 370.0,
      housePrice: 470.0,
      services: [10, 11, 12],
    },
    {
      id: 8,
      name: "Duo",
      condo: true,
      house: true,
      condoPrice: 285.0,
      housePrice: 365.0,
      services: [1, 2, 0, 11, 12],
    },
  ]);
};
