export default (req, res) => {
  res.statusCode = 200;
  res.json([
    {
      id: 1,
      name: "Property Photos",
      price: 100.0,
      category: "photo",
      class: "Condo",
      description:
        "Includes 20 professionally edited photos of high quality, color balance, exposure and sharpening.",
      packages: [
        "deluxe",
        "deluxePlus",
        "fullCoverage",
        "fullCoveragePlus",
        "basics",
        "basicsPlus",
        "duo",
      ],
    },
    {
      id: 2,
      name: "Property Photos",
      price: 150.0,
      category: "photo",
      class: "House",
      description:
        "Includes 35 professionally edited photos of high quality, color balance, exposure and sharpening.",
      packages: [
        "deluxe",
        "deluxePlus",
        "fullCoverage",
        "fullCoveragePlus",
        "basics",
        "basicsPlus",
        "duo",
      ],
    },
    {
      id: 3,
      name: "10 Extra Photos",
      price: 20.0,
      category: "photo",
      class: "",
      description: "",
      packages: [],
    },
    {
      id: 4,
      name: "Virtual Home Staging*",
      price: 30.0,
      category: "photo",
      class: "",
      description: "Price per room. Does not include property photos.",
      packages: [],
    },
    {
      id: 5,
      name: "HQ 3D Virtual Tour*",
      price: 250.0,
      category: "3d",
      class: "Condo",
      description:
        "3D tour with Matterport camera for condos, lofts and apartments that are a single floor.",
      packages: ["deluxePlus", "fullCoveragePlus", "basicsPlus"],
    },
    {
      id: 6,
      name: "HQ 3D Virtual Tour*",
      price: 400.0,
      category: "3d",
      class: "House",
      description: "3D tour with Matterport camera for 2+ floor properties.",
      packages: ["deluxePlus", "fullCoveragePlus", "basicsPlus"],
    },
    {
      id: 7,
      name: "3D Virtual Tour*",
      price: 135.0,
      category: "3d",
      class: "Condo",
      description:
        "3D tour for condos, lofts and apartments that are a single floor.",
      packages: ["deluxe", "fullCoverage", "basics"],
    },
    {
      id: 8,
      name: "3D Virtual Tour*",
      price: 150.0,
      category: "3d",
      class: "House",
      description: "3D tour for 2+ floor properties.",
      packages: ["deluxe", "fullCoverage", "basics"],
    },
    {
      id: 9,
      name: "Drone Video",
      price: 200.0,
      category: "video",
      class: "",
      description:
        "Includes filming the exterior of the property and a 30-60 second edit.",
      packages: ["deluxe", "fullCoverage", "basics", "fullVideo", "duo"],
    },
    {
      id: 10,
      name: "HDR Drone Video",
      price: 250.0,
      category: "video",
      class: "",
      description:
        "Includes filming the exterior of the property in HDR with detailed coloring and fixed windows 60 second edit.",
      packages: ["deluxePlus", "fullCoveragePlus", "basicsPlus"],
    },
    {
      id: 11,
      name: "HDR Interior Video",
      price: 200.0,
      category: "video",
      class: "Condo",
      description:
        "Includes filming the interior of the property in HDR with detailed coloring, 60 second edit.",
      packages: ["deluxe", "deluxePlus", "fullVideo", "duo"],
    },
    {
      id: 12,
      name: "HDR Interior Video",
      price: 250.0,
      category: "video",
      class: "House",
      description:
        "Includes filming the interior of the property in HDR with detailed coloring, 60 second edit.",
      packages: ["deluxe", "deluxePlus", "fullVideo", "duo"],
    },
    {
      id: 13,
      name: "1-Day Rush Delivery",
      price: 100.0,
      category: "addons",
      class: "",
      description: "",
      packages: [],
    },
    {
      id: 14,
      name: "Matterport Storage",
      price: 15.0,
      category: "addons",
      class: "",
      description: "Includes an extra 3 months of storage.",
      packages: [],
    },
  ]);
};
